name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Debug
        run: dir

      - name: Stop old containers
        run: docker compose down

      - name: Build and start
        run: docker compose up -d --build

      - name: Wait
        run: timeout /t 10

      - name: Run tests
        run: docker exec flaskapp pytest
